name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Permissions to Run gradlew
        run: 	chmod +x ./fabric/gradlew && chmod +x ./annotation-processor/gradlew && chmod +x ./forge/gradlew

      - name: Build Fabric
        run: cd fabric && ./gradlew build && cd ..

      - name: Build Forge
        run: cd forge && ./gradlew build && cd ..

      - name: Remove Sources Jar
        run: rm -f fabric/build/libs/*-sources.jar && rm -f forge/build/libs/*-sources.jar

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fabric-artifact
          path: fabric/build/libs/*.jar

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: forge-artifact
          path: forge/build/libs/*.jar